name: heistom
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  freezed_annotation: ^3.0.0
  get: ^4.7.2
  intl: ^0.20.2
  json_annotation: ^4.8.1
  latlong2: ^0.9.1
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.6
  fl_chart: ^1.0.0
  dio: ^5.8.0+1
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_otp_text_field: ^1.1.0+2
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
  flutter_staggered_grid_view: ^0.7.0
  flutter_typeahead: ^5.2.0
  shared_preferences: ^2.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

dependency_overrides:
  analyzer: 7.3.0
